### ISSUE TITLE
Jtwig Integration

### ISSUE THREAD

**Issue by joao-de-melo** [warhuhn/warhuhn-spark-template-jtwig#3]
Hi @warhuhn,

this seems to be a nice integration. What do you think about moving it to the jtwig organization and become a jtwig committer responsible for the spark integration?

Regards

**Comment by warhuhn** [comment]
Hi,

i just added some form of Maven integration, now Users can add it as a dependency.

I don' think it is necessary to move the entire Project to JTwig.
